core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('services/', include('services.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from .views import *

app_name = 'services'

urlpatterns = [
    path('', services_view, name = 'index'),
    path('machine_learning', ml_view, name = 'machine_learning'),
    path('machine_learning/arka', arka_view, name = 'arka'),
    path('machine_learning/import', import_view, name = 'import'),
    path('machine_learning/train', train_view, name = 'train'),
    path('machine_learning/success_upload', success_upload_view, name = 'success_upload'),

]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name = 'index')

]

services/models.py
from django.db import models
from django.contrib.auth.models import User

class Csv(models.Model):
    
    file_name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to='upload')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    

    def __str__(self) -> str:
        return self.file_name

website/models.py
from django.db import models

# Create your models here.

services/forms.py
from django import forms
from .models import Csv

class CsvForm(forms.ModelForm):
    
    class Meta:
        model = Csv
        fields = ['file_name', 'file']

services/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import CsvForm
from .models import Csv
import h2o
from h2o.automl import H2OAutoML
import pandas as pd
import os
from django.conf import settings


def services_view(request):
    return render(request, 'services/index.html')

def ml_view(request):
    return render(request, 'services/machine_learning.html')

def arka_view(request):
    return render(request, 'services/arka.html')


def import_view(request):
    if request.method == "POST":
        form = CsvForm(request.POST, request.FILES)
        if form.is_valid():
            csv_instance = form.save(commit=False)
            csv_instance.user = request.user  
            csv_instance.save()
            msg = 'Successful'
            return redirect('/services/machine_learning/success_upload')
    else:
        form = CsvForm()
    context = {'form': form}
    return render(request, 'services/import.html', context)
'''
from django.forms.widgets import Table, TableHead, TableBody, Row, Cell

def html_table_from_df(df, table_name):
    # Define table head
    table_head = TableHead(cells=[Cell(str(column)) for column in df.columns])
    
    # Define table rows
    table_rows = []
    for index, row in df.iterrows():
        table_rows.append(Row(cells=[Cell(str(value)) for value in row]))
    
    # Define table body
    table_body = TableBody(rows=table_rows)
    
    # Define table
    table = Table(head=table_head, body=table_body, name=table_name)
    
    # Convert table to HTML string
    html_table = str(table)
    
    return html_table
'''

def train_view(request):
    if request.method == 'POST':
        file = os.path.join(settings.MEDIA_ROOT, request.POST.get('dataset'))
        df = pd.read_csv(file)
        column_names = df.columns.tolist()
        range = [1,2,3,4,5,6,7,8,9,10]
        context = {'user_csvs': Csv.objects.filter(user=request.user), 'column_names': column_names, 'range': range}
        if (request.POST.get('column_names') != None) & (request.POST.get('number') != None):
            h2o.init()  # شروع H2O
            h2o_df = h2o.H2OFrame(df)
            y = request.POST.get('column_names')
            #h2o_df[y] = h2o_df[selected_column].asfactor()  
            aml = H2OAutoML(max_models=int(request.POST.get('number')), seed=1)
            aml.train(y=y, training_frame=h2o_df)
            
            # دریافت نتایج
            leaderboard = aml.leaderboard
            results = leaderboard.as_data_frame()
            
            table = results
            # برگرداندن نتایج به صورت JSON
            return render(request, 'services/leaderboard.html', {'leaderboard': table})
        
        return render(request, 'services/train.html', context)
        
    else:
        user_csvs = Csv.objects.filter(user=request.user)
        range = [1,2,3,4,5,6,7,8,9,10]
        context = {'user_csvs': user_csvs, 'range': range}
        
        return render(request, 'services/train.html', context)


def success_upload_view (request):
    return render(request, 'services/success_upload.html')

website/views.py
from django.shortcuts import render, redirect

def index_view(request):
    
    return render(request, 'website/index.html')

templates/services/import.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>

    .service-section-wrapper {
        margin: 0 auto;
        text-align: center;
        align-items: center;
        align-self: center;
        font-family: 'Vazir';
        font-style: inherit;
    }
</style>

<!--
<div class="col-lg-6 align-self-end text-center text-lg-end">
                <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 400px;">
            </div>

            <div class="col-lg-6 align-self-center text-center text-lg-end mb-lg-5" style="font-family: 'Iranian Sans'; font-style: bold;">
                <h1 class="display-4 text-white mb-4 animated slideInRight"> ماشین لرنینگ </h1>
                
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center justify-content-lg-end mb-0">
                        <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Our Services</li>
                    </ol>
                </nav>
-->

<!-- Hero Start -->

<div class="container-fluid pt-5 bg-primary hero-header mb-2">
    <div class="container pt-5">
        
    </div>
</div>

<!-- Hero End -->



<!-- Full Screen Search Start -->
<div class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content" style="background: rgba(20, 24, 62, 0.7);">
            <div class="modal-header border-0">
                <button type="button" class="btn btn-square bg-white btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                <div class="input-group" style="max-width: 600px;">
                    <input type="text" class="form-control bg-transparent border-light p-3"
                        placeholder="Type search keyword">
                    <button class="btn btn-light px-4"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Full Screen Search End -->

<div class="container-fluid bg-light py-2">
    <div class="container py-1">
      <div class="row g-1 align-items-center">
        <div class="service-section-wrapper">
          <section class="service-section bg-light py-2">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-lg-12">
                  <div class="d-flex flex-wrap justify-content-between">
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">داشبورد</a>
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">مدل ها</a>
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">خوشه بندی</a>
                    <a href="{% url 'services:train' %}" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">پیش بینی</a>
                    <a href="{% url 'services:import' %}" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">ورود داده</a>
                    <a href="{% url 'services:machine_learning' %}" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">خانه</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
</div>

<div class="container-fluid bg-light py-1">
    <div class="container py-1">
        <div class="row g-1 align-items-center">
            <div class="service-section-wrapper">
                <section class="service-section bg-light py-2">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-lg-12">
                                <div class="d-flex flex-wrap justify-content-between">
                                    <!-- Your buttons here -->
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>

        <div class="row g-4 align-items-center">
            <div class="col-lg-9 wow fadeIn" data-wow-delay="0.1s">
                <div class="row align-items-center">
                    <div class="col-md-9 mx-auto">
                        <div class="text-center">
                            <h1> </h1>
                            <form method="post" enctype="multipart/form-data" action="{% url 'services:import' %}">
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-md-12">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="file_name" placeholder="Your Name">
                                            <label for="name">نام فایل</label>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-floating">
                                            <input type="file" class="form-control" name="file">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100 py-3" type="submit">بارگذاری</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 wow fadeIn" data-wow-delay="0.5s" style="text-align: right;">
                <h2 class="mb-8" style="font-family: Vazir;">ورود داده </h2>
                <p>از این قسمت میتوانید داده های خود را به سامانه وارد کنید</p>
                <p>از این قسمت میتوانید داده های خود را به سامانه وارد کنید</p>
                <p>از این قسمت میتوانید داده های خود را به سامانه وارد کنید</p>
                <p>از این قسمت میتوانید داده های خود را به سامانه وارد کنید</p>
                <div class="col-lg-12 wow fadeIn" data-wow-delay="0.1s" style="text-align: left;">
                    <a class="btn btn-primary rounded-pill px-4" style="font-family: Vazir;" href="">مشاهده داده ها </a>
                </div>
            </div>
        </div>
    </div>
</div>



      
    <!-- Testimonial Start -->
    <div class="container-xxl py-5">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-5 wow fadeIn" data-wow-delay="0.1s">
                    <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">Testimonial</div>
                    <h1 class="mb-4">What Say Our Clients!</h1>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam
                        amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus
                        clita duo justo et tempor eirmod magna dolore erat amet</p>
                    <a class="btn btn-primary rounded-pill px-4" href="">Read More</a>
                </div>
                <div class="col-lg-7 wow fadeIn" data-wow-delay="0.5s">
                    <div class="owl-carousel testimonial-carousel border-start border-primary">
                        <div class="testimonial-item ps-5">
                            <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                            <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                            <div class="d-flex align-items-center">
                                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-1.jpg' %}"
                                    style="width: 60px; height: 60px;">
                                <div class="ps-3">
                                    <h5 class="mb-1">Client Name</h5>
                                    <span>Profession</span>
                                </div>
                            </div>
                        </div>
                        <div class="testimonial-item ps-5">
                            <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                            <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                            <div class="d-flex align-items-center">
                                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-2.jpg' %}"
                                    style="width: 60px; height: 60px;">
                                <div class="ps-3">
                                    <h5 class="mb-1">Client Name</h5>
                                    <span>Profession</span>
                                </div>
                            </div>
                        </div>
                        <div class="testimonial-item ps-5">
                            <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                            <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                            <div class="d-flex align-items-center">
                                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-3.jpg' %}"
                                    style="width: 60px; height: 60px;">
                                <div class="ps-3">
                                    <h5 class="mb-1">Client Name</h5>
                                    <span>Profession</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->


    <!-- Newsletter Start -->
    <div class="container-fluid bg-primary newsletter py-5">
        <div class="container">
            <div class="row g-5 align-items-center">
                <div class="col-md-5 ps-lg-0 pt-5 pt-md-0 text-start wow fadeIn" data-wow-delay="0.3s">
                    <img class="img-fluid" src="{% static 'img/newsletter.png' %}" alt="">
                </div>
                <div class="col-md-7 py-5 newsletter-text wow fadeIn" data-wow-delay="0.5s">
                    <div class="btn btn-sm border rounded-pill text-white px-3 mb-3">Newsletter</div>
                    <h1 class="text-white mb-4">Lets subscribe the newsletter</h1>
                    <div class="position-relative w-100 mt-3 mb-2">
                        <input class="form-control border-0 rounded-pill w-100 ps-4 pe-5" type="text"
                            placeholder="Enter Your Email" style="height: 48px;">
                        <button type="button" class="btn shadow-none position-absolute top-0 end-0 mt-1 me-2"><i
                                class="fa fa-paper-plane text-primary fs-4"></i></button>
                    </div>
                    <small class="text-white-50">Diam sed sed dolor stet amet eirmod</small>
                </div>
            </div>
        </div>
    </div>
    <!-- Newsletter End -->


{% endblock %}

templates/services/leaderboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaderboard</title>
    <!-- لینک کتابخانه Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1>Leaderboard</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <!-- نام ستون‌ها -->
                        <th>رتبه</th>
                        <th>مدل</th>
                        <th>امتیاز</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- اطلاعات ردیف‌ها -->
                    {% for index, row in leaderboard.iterrows %}
                        <tr>
                            <td>{{ index|add:1 }}</td>

                            <td>{{ row.model_id }}</td>
                            <td>{{ row.auc }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- لینک اسکریپت‌های Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

<div class="container">
    <h1>Leaderboard</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <!-- نمایش نام ستون‌ها -->
                    {% for column_name in column_names %}
                        <th>{{ column_name }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <!-- نمایش رکوردها -->
                {% for index, row in leaderboard.iterrows %}
                    <tr>
                        <!-- نمایش مقادیر مربوط به هر ستون -->
                        {% for column_name in column_names %}
                            <td>{{ row.column_name }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/services/machine_learning.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .service-item {
      color: blue;
      font-size: 16px;
      transition: color 0.3s, font-size 0.3s;
    }
    
    .service-item:hover {
      color: white;
      font-size: 14px;
    }
    .service-section-wrapper {
      margin: 0 auto;
      text-align: center;
      align-items: center;
      align-self: center;
      font-family: 'Vazir';
      font-style: inherit;
    }
    

  </style>

  <!-- 
<div class="col-lg-6 align-self-end text-center text-lg-end">
                <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 400px;">
            </div>

            <div class="col-lg-6 align-self-center text-center text-lg-end mb-lg-5" style="font-family: 'Iranian Sans'; font-style: bold;">
                <h1 class="display-4 text-white mb-4 animated slideInRight"> ماشین لرنینگ </h1>
                
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center justify-content-lg-end mb-0">
                        <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Our Services</li>
                    </ol>
                </nav>
 -->

  <!-- Hero Start -->

  <div class="container-fluid pt-5 bg-primary hero-header mb-2">
    <div class="container pt-5"></div>
  </div>

  <!-- Hero End -->

  <!-- Full Screen Search Start -->
  <div class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content" style="background: rgba(20, 24, 62, 0.7);">
        <div class="modal-header border-0">
          <button type="button" class="btn btn-square bg-white btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex align-items-center justify-content-center">
          <div class="input-group" style="max-width: 600px;">
            <input type="text" class="form-control bg-transparent border-light p-3" placeholder="Type search keyword" />
            <button class="btn btn-light px-4"><i class="bi bi-search"></i></button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Full Screen Search End -->

  <!-- Service Start -->
  <div class="container-fluid bg-light py-2">
    <div class="container py-1">
      <div class="row g-1 align-items-center">

        <!--
        <div class="service-section-wrapper">
          <section class="service-section bg-light py-2">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-lg-12">
                  <div class="d-flex flex-wrap justify-content-between">
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">داشبورد</a>
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">مدل ها</a>
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">خوشه بندی</a>
                    <a href="#" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">پیش بینی</a>
                    <a href="{% url 'services:import' %}" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">ورود داده</a>
                    <a href="{% url 'services:machine_learning' %}" class="service-item d-flex flex-column justify-content-center text-center rounded mb-2" style="width: 150px; height: 10px; margin-right: 0; margin-top: 0">خانه</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
    -->

    <div class="row g-4 align-items-center">
        <div class="col-lg-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="about-img">
                <img class="img-fluid" src="{% static 'img/about-img.jpg' %}" style="width: auto;">
            </div>
        </div>
        <div class="col-lg-7 wow fadeIn" data-wow-delay="0.5s" style="text-align: right;">
            <h1 class="mb-4" style="font-family: Vazir; color: #226BCE;">ARKA </h1>
            <h4 class="mb-4" style="font-family: Vazir;">پلتفرم یادگیری ماشین بعنوان خدمت</h4> 
            <p class="mb-4" style="font-family: Vazir; font-size: 14px ; color: #9299A2 ;" >آرکا یک پلتفرم یادگیری ماشین به عنوان خدمت است با شعار هوش مصنوعی برای همه به کاربران با سطوح مختلف دانش فنی، از مبتدی تا متخصص، امکان می‌دهد تا از قدرت هوش مصنوعی برای حل مسائل و ارتقای کارایی خود استفاده کنند</p>
            <ul class="list-unstyled" style="font-family: Vazir; color: #9299A2 ;font-size: 14px ;">
                <li style="color: #9299A2 ;font-size: 14px ;">
                    <strong>زیرساخت:</strong> آرکا تمام زیرساخت‌های لازم برای اجرای الگوریتم‌های هوش مصنوعی را فراهم می‌کند، به این معنی که کاربران نیازی به نگرانی در مورد سرورها، ذخیره‌سازی یا شبکه ندارند
                </li>
                <li style="color: #9299A2 ;font-size: 14px ;">
                    <strong>الگوریتم‌ها:</strong> آرکا مجموعه‌ای از الگوریتم‌های یادگیری ماشین پیش‌ساخته را ارائه می‌دهد که کاربران می‌توانند از آنها برای انجام وظایف مختلف مانند طبقه‌بندی،خوشه‌بندی و ... استفاده کنند
                </li>
                <li style="color: #9299A2 ;font-size: 14px ;">
                    <strong>ابزارها:</strong> آرکا ابزارهایی را برای پیش پردازش داده‌ها، آموزش مدل‌ها، ارزیابی عملکرد و استقرار مدل‌ها در محیط‌های عملیاتی ارائه می‌دهد
                </li>
            </ul>
            <div class="col-lg-12 wow fadeIn" data-wow-delay="0.1s" style="text-align: left;">
                <a class="btn btn-primary rounded-pill px-4" style="font-family: Vazir;" href="{% url 'services:arka' %}">شروع کار با آرکا </a>
            </div>
        </div>
    </div>
    
                
                
            </div>
        </div>
        
      </div>
    </div>
  </div>
  <!-- Service End -->

  <!-- Testimonial Start -->
  <div class="container-xxl py-5">
    <div class="container py-5">
      <div class="row g-5">
        
        <div class="col-lg-7 wow fadeIn" data-wow-delay="0.5s">
          <div class="owl-carousel testimonial-carousel border-start border-primary">
            <div class="testimonial-item ps-5">
              <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
              <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
              <div class="d-flex align-items-center">
                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-1.jpg' %}" style="width: 60px; height: 60px;" />
                <div class="ps-3">
                  <h5 class="mb-1">Client Name</h5>
                  <span>Profession</span>
                </div>
              </div>
            </div>
            <div class="testimonial-item ps-5">
              <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
              <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
              <div class="d-flex align-items-center">
                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-2.jpg' %}" style="width: 60px; height: 60px;" />
                <div class="ps-3">
                  <h5 class="mb-1">Client Name</h5>
                  <span>Profession</span>
                </div>
              </div>
            </div>
            <div class="testimonial-item ps-5">
              <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
              <p class="fs-4">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
              <div class="d-flex align-items-center">
                <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-3.jpg' %}" style="width: 60px; height: 60px;" />
                <div class="ps-3">
                  <h5 class="mb-1">Client Name</h5>
                  <span>Profession</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">Testimonial</div>
            <h1 class="mb-4">What Say Our Clients!</h1>
            <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
            <a class="btn btn-primary rounded-pill px-4" href="">Read More</a>
          </div>

      </div>
    </div>
  </div>
  <!-- Testimonial End -->

  <!-- Newsletter Start -->
  <div class="container-fluid bg-primary newsletter py-5">
    <div class="container">
      <div class="row g-5 align-items-center">
        <div class="col-md-5 ps-lg-0 pt-5 pt-md-0 text-start wow fadeIn" data-wow-delay="0.3s">
          <img class="img-fluid" src="{% static 'img/newsletter.png' %}" alt="" />
        </div>
        <div class="col-md-7 py-5 newsletter-text wow fadeIn" data-wow-delay="0.5s">
          <div class="btn btn-sm border rounded-pill text-white px-3 mb-3">Newsletter</div>
          <h1 class="text-white mb-4">Lets subscribe the newsletter</h1>
          <div class="position-relative w-100 mt-3 mb-2">
            <input class="form-control border-0 rounded-pill w-100 ps-4 pe-5" type="text" placeholder="Enter Your Email" style="height: 48px;" />
            <button type="button" class="btn shadow-none position-absolute top-0 end-0 mt-1 me-2"><i class="fa fa-paper-plane text-primary fs-4"></i></button>
          </div>
          <small class="text-white-50">Diam sed sed dolor stet amet eirmod</small>
        </div>
      </div>
    </div>
  </div>
  <!-- Newsletter End -->
{% endblock %}

templates/upload/import.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload CSV</title>
</head>
<body>
    <h1>Upload CSV</h1>
    {% if msg %}
        <p>{{ msg }}</p>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    {% if file_content %}
        <p>Uploaded file content: {{ file_content }}</p>
    {% endif %}
</body>
</html>